### ISSUE TITLE
URL to print server wont seem to work??

### ISSUE THREAD

**Issue by thestraycat** [Westwoodlabs/web2dymo-docker#12]
Hi there,
I know this isnt technically an issue per se, but this is quite a niche project and i was wondering whether you could list the format or a 'working' example for the socket line in the docker compose file (PRINTER1_DEVURI: socket://url.to.print.server:9100)? 

Im a little unclear on what the URL should be... in my instance the print server runs on IP address 192.168.1.30 would this line simply be:

PRINTER1_DEVURI: socket://192.168.1.30:9100 

If so, i'd have expected the variable example it to read (PRINTER1_DEVURI: socket://IP.to.print.server:9100)

Any help would be really appreciated!

**Comment by thestraycat** [comment]
Thanks for your reply - Mine would be usb to print server too. So in your example what would your docker variable look like for:

PRINTER1_DEVURI: socket://192.168.1.30:9100

**Comment by TinkerTob** [comment]
I'm using a Dymo LW400 printer with a Raspberry Pi as a server, and I remember that it was a bit of a struggle getting it to work.

What I ended up with was:
```
environment:
      PRINTER1_ENABLE: 1
      PRINTER1_NAME: dymo400
      PRINTER1_DEVURI: ipp://dymo:631/printers/LW400Raw
      PRINTER1_PPDFILE: /usr/share/cups/model/lw400.ppd
```
...where `dymo` is the local hostname of my CUPS print server (`192.168.1.30` in your case).

I kind of remember having to download the lw400.ppd driver myself and putting it `/usr/share/cups/model/`. But it's been over a year and I might be confusing this with the manual setup of the Pi print server, so I really can't tell you any more details.
